---
- name: Get Vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
    validate_certs: false
    dest: "./vector-{{ vector_version }}.deb"
    mode: "01204"
- name: Install Vector packages
  ansible.builtin.apt:
    deb: ./vector-{{ vector_version }}.deb
    state: present
  notify: Start vector service
