---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos
    image: docker.io/centos:7
    pre_build_image: false
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
  - name: ubuntu
    image: tomaevmax/ubuntu:1
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
