---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: centos_7
    image: centos:7
    dockerfile: ../../resources/Dockerfile.j2
    # pre_build_image: true
    command: /usr/sbin/init
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
provisioner:
  name: ansible
verifier:
  name: ansible
