---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: centos_7
    image: docker.io/pycontribs/centos:7
    # dockerfile: ../../resources/Dockerfile.j2
    pre_build_image: true
    command: /sbin/init && sleep 5000000
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
provisioner:
  name: ansible
verifier:
  name: ansible
